%------------------------------------------------------------------------------
% File     : SWV051+1 : ILTP v1.1.1
% Domain   : Software Verification
% Problem  : Unsimplified proof obligation cl5_nebula_norm_0025
% Version  : [DFS04] axioms : Especial.
% English  : Proof obligation emerging from the norm-safety verification for
%            the cl5_nebula program. norm-safety ensures that the contents of
%            certain one-dimensional arrays add up to one.

% Refs     : [Fis04] Fischer (2004), Email to G. Sutcliffe
%          : [DFS04] Denney et al. (2004), Using Automated Theorem Provers
% Source   : [Fis04]
% Names    : cl5_nebula_norm_0025 [Fis04]

% Status   : Theorem
% Rating   : 1.00 v3.1.0
%
% Status (intuit.) : Open
% Rating (intuit.) : 1.00 v1.1.0
%
% Syntax   : Number of formulae    :   83 (  48 unit)
%            Number of atoms       :  208 (  83 equality)
%            Maximal formula depth :   24 (   4 average)
%            Number of connectives :  130 (   5 ~  ;  17  |;  72  &)
%                                         (   5 <=>;  31 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :    6 (   1 propositional; 0-2 arity)
%            Number of functors    :   42 (  22 constant; 0-4 arity)
%            Number of variables   :  141 (   0 singleton; 141 !;   0 ?)
%            Maximal term depth    :    9 (   1 average)

% Comments : 
%------------------------------------------------------------------------------
%----Include NASA software certification axioms
include('Axioms/SWV003+0.ax').
%------------------------------------------------------------------------------
%----Proof obligation generated by the AutoBayes/AutoFilter system
fof(cl5_nebula_norm_0025,conjecture,
    ( ( pv86 = sum(n0,minus(n5,n1),divide(abs(minus(a_select2(mu,pv87),a_select2(muold,pv87))),plus(abs(a_select2(mu,pv87)),abs(a_select2(muold,pv87)))))
      & pv88 = sum(n0,minus(n5,n1),divide(abs(minus(a_select2(rho,pv89),a_select2(rhoold,pv89))),plus(abs(a_select2(rho,pv89)),abs(a_select2(rhoold,pv89)))))
      & pv90 = sum(n0,minus(pv75,n1),divide(abs(minus(a_select2(sigma,pv91),a_select2(sigmaold,pv91))),plus(abs(a_select2(sigma,pv91)),abs(a_select2(sigmaold,pv91)))))
      & leq(n0,pv75)
      & leq(pv75,minus(n5,n1)) )
   => ( plus(pv90,divide(abs(minus(a_select2(sigma,pv75),a_select2(sigmaold,pv75))),plus(abs(a_select2(sigma,pv75)),abs(a_select2(sigmaold,pv75))))) = sum(n0,minus(plus(n1,pv75),n1),divide(abs(minus(a_select2(sigma,pv91),a_select2(sigmaold,pv91))),plus(abs(a_select2(sigma,pv91)),abs(a_select2(sigmaold,pv91)))))
      & pv86 = sum(n0,minus(n5,n1),divide(abs(minus(a_select2(mu,pv87),a_select2(muold,pv87))),plus(abs(a_select2(mu,pv87)),abs(a_select2(muold,pv87)))))
      & pv88 = sum(n0,minus(n5,n1),divide(abs(minus(a_select2(rho,pv89),a_select2(rhoold,pv89))),plus(abs(a_select2(rho,pv89)),abs(a_select2(rhoold,pv89))))) ) )).

%----Automatically generated axioms

fof(gt_5_4,axiom,
    ( gt(n5,n4) )).

fof(gt_4_tptp_minus_1,axiom,
    ( gt(n4,tptp_minus_1) )).

fof(gt_5_tptp_minus_1,axiom,
    ( gt(n5,tptp_minus_1) )).

fof(gt_0_tptp_minus_1,axiom,
    ( gt(n0,tptp_minus_1) )).

fof(gt_1_tptp_minus_1,axiom,
    ( gt(n1,tptp_minus_1) )).

fof(gt_2_tptp_minus_1,axiom,
    ( gt(n2,tptp_minus_1) )).

fof(gt_3_tptp_minus_1,axiom,
    ( gt(n3,tptp_minus_1) )).

fof(gt_4_0,axiom,
    ( gt(n4,n0) )).

fof(gt_5_0,axiom,
    ( gt(n5,n0) )).

fof(gt_1_0,axiom,
    ( gt(n1,n0) )).

fof(gt_2_0,axiom,
    ( gt(n2,n0) )).

fof(gt_3_0,axiom,
    ( gt(n3,n0) )).

fof(gt_4_1,axiom,
    ( gt(n4,n1) )).

fof(gt_5_1,axiom,
    ( gt(n5,n1) )).

fof(gt_2_1,axiom,
    ( gt(n2,n1) )).

fof(gt_3_1,axiom,
    ( gt(n3,n1) )).

fof(gt_4_2,axiom,
    ( gt(n4,n2) )).

fof(gt_5_2,axiom,
    ( gt(n5,n2) )).

fof(gt_3_2,axiom,
    ( gt(n3,n2) )).

fof(gt_4_3,axiom,
    ( gt(n4,n3) )).

fof(gt_5_3,axiom,
    ( gt(n5,n3) )).

fof(finite_domain_4,axiom,
    ( ! [X] : 
        ( ( leq(n0,X)
          & leq(X,n4) )
       => ( X = n0
          | X = n1
          | X = n2
          | X = n3
          | X = n4 ) ) )).

fof(finite_domain_5,axiom,
    ( ! [X] : 
        ( ( leq(n0,X)
          & leq(X,n5) )
       => ( X = n0
          | X = n1
          | X = n2
          | X = n3
          | X = n4
          | X = n5 ) ) )).

fof(finite_domain_0,axiom,
    ( ! [X] : 
        ( ( leq(n0,X)
          & leq(X,n0) )
       => X = n0 ) )).

fof(finite_domain_1,axiom,
    ( ! [X] : 
        ( ( leq(n0,X)
          & leq(X,n1) )
       => ( X = n0
          | X = n1 ) ) )).

fof(finite_domain_2,axiom,
    ( ! [X] : 
        ( ( leq(n0,X)
          & leq(X,n2) )
       => ( X = n0
          | X = n1
          | X = n2 ) ) )).

fof(finite_domain_3,axiom,
    ( ! [X] : 
        ( ( leq(n0,X)
          & leq(X,n3) )
       => ( X = n0
          | X = n1
          | X = n2
          | X = n3 ) ) )).

fof(successor_4,axiom,
    ( succ(succ(succ(succ(n0)))) = n4 )).

fof(successor_5,axiom,
    ( succ(succ(succ(succ(succ(n0))))) = n5 )).

fof(successor_1,axiom,
    ( succ(n0) = n1 )).

fof(successor_2,axiom,
    ( succ(succ(n0)) = n2 )).

fof(successor_3,axiom,
    ( succ(succ(succ(n0))) = n3 )).
%------------------------------------------------------------------------------
